date util: utcOffset 추가 및 format 수정
day1co/pebbles pull request #47
Opened 2021-11-17 14:46 UTC by moonimooni

## PR 의 종류는 어떤 것인가요?

- [ ] 버그 수정
- [x] 새로운 기능
- [ ] 리팩토링

## 수정이 필요하게된 이유가 무엇인가요? (Jira 이슈가 있다면 링크를 연결해주세요)

## 무엇을 어떻게 변경했나요?
- utcOffset 구현 -> 동사형인 offsetUTC로 함수명 변경
- format함수에 분기 추가. default format 인자 추가

## 코드 변경을 이해하기 위한 배경지식이 필요하다면 설명 해주세요.
- 기존 dateUtil의 utcOffset 결과물은 Moment<>의 instance였는데, 여기서 offset값이 있냐 없냐에 따라 UTC로 표현되기도, GMT로 표현되기도 합니다. (`Moment<2020-01-01T03:00:00+03:00>` or `Moment<2020-01-01T00:00:00Z>`)
이와 유사하게 가기 위해 Date를 상속받은 임의의 class를 만들어 해당 클래스 인스턴스에 offset property를 부여하는 방식으로 접근해봤습니다.

- utcOffset은 결과값이 그대로 쓰이지 않고 항상 format함수가 그 값을 감싸는 방식으로 사용되기에 format함수의 수정도 필요했습니다.
- 기존의 format 함수는 런타임 로컬 타임존에 영향을 받기 때문에 그대로 사용했다가는 utc offset값이 두배가 되어버려서...

ex
```javascript
format(DateUtil.offsetUTC(new Date('2000-01-01 00:00:00Z'), 540)) // => 2000-01-01T18:00:00+09:00 ?!?! 
```

따라서 offsetUTC의 결과물이라면 UTC를 기준으로 연,월,일 등을 가지고 와서 포맷하도록 작성하였습니다.

## 디펜던시 변경이 있나요?

## 어떻게 테스트 하셨나요?
테스트코드

## 코드의 실행결과를 볼 수 있는 로그가 있다면 첨부해주세요.
<img width="336" alt="Screen Shot 2021-11-17 at 11 14 09 PM" src="https://user-images.githubusercontent.com/63729090/142216782-c21e5da7-56bf-4bad-b332-f325379e4cd1.png">

2021-11-18 02:09 UTC, hibiyasleep commented
UTC 자체는 세계협정시라는 뜻이고 UTC Offset은 UTC 기준의 시차를 뜻하는 단어라... UTC를 offset한다고 쓰면 틀린 표현이 되지 않을까 싶습니다
`set(Timezone)?Offset` 정도가 어떨까요

2021-11-18 05:26 UTC, moonimooni commented
> UTC 자체는 세계협정시라는 뜻이고 UTC Offset은 UTC 기준의 시차를 뜻하는 단어라... UTC를 offset한다고 쓰면 틀린 표현이 되지 않을까 싶습니다 offset이라는 단어에서... 예를 들면... `.offsetUTC('...+0900', 9 * 60)` 하면 +1800이 되게 동작할거라고 예상되기도 하고요 `setHours` 같은 메소드들이랑 맞추는 김에 `set(Timezone|UTC)?Offset` 정도가 어떨까요

좋은 이름 제안 감사합니다! 훨씬 나은것 같네요 🙌🏻

2021-11-19 06:15 UTC, hibiyasleep approved these changes

2021-11-23 02:32 UTC, rageatm commented on src/date-util/date-util.ts
> +) {
```suggestion
interface DateInfo {  // interface 파일에 작성
  year
  month
  day
  hour
  minute
  second
  millisecond
}

function replaceDateFormat(format: string, dateInfo: DateInfo) {
```

2021-11-23 03:49 UTC, moonimooni commented on src/date-util/date-util.ts
> +) {
수정했습니다!

2021-11-23 03:51 UTC, moonimooni commented
offset 표기시 (ex: HH:mm:ss[+-]hh:mm) UTC기준 + 시차밖에 표기가 안되었던 문제가 있어서 마이너스 시차도 받을 수 있도록 (ex: 미국 뉴욕은 -05:00)해당 부분도 수정했습니다.

2021-12-07 00:24 UTC, iolo requested changes
moment를 빼고 Day1D를 추가? 이건 좀 곤란할 듯...

2021-12-14 07:04 UTC, moonimooni commented
기존 moment에서는 Moment 객체가 가진 `isUtc`나, `isUtcOffset` 같은 프로퍼티로 format시 utc 기준의 string 결과물을 내야 하는지, 로컬 타임 기준으로 format해야 하는지 구분했던 것으로 보입니다. 

순수 자바스크립트로 구현해야 한다 가정했을때, 자체적인 클래스 없이는 위와 같이 구현할 수 있을지 모르겠어서... 
아예 format시에 UTC 기준으로 반환할지 여부를 option 파라미터로 주입하도록 생각해보았는데요
이 방법이 무리인듯 싶으면 dayjs같은 외부 의존성을 주입하는게 어떨까 생각합니다.

2021-12-24 02:58 UTC, iolo commented on src/date-util/date-util.ts
> +  }
자바스크립트 Date는 내부적으로는 UTC기반의 epoch을 사용합니다
이거면 충분하지 않을까요?
```js
return new Date(d.getTime() + offsetMinute * ONE_SECOND * ONE_MINUTE_IN_SECOND));
```

2021-12-24 03:02 UTC, iolo commented on src/date-util/date-util.ts
> +          return `${dateInfo.year}`;
숫자하나를 문자열로 만드는데 `${number}`가 필요할까요? 그냥 `number.toString()` 또는 `String(number)`은 어떨까요?

2021-12-24 03:05 UTC, iolo commented on src/date-util/date-util.ts
> +    if (format === DEFAULT_LOCALE_DATE_FORMAT) {
이  if 문은 format을 정규식 파싱해서 처리하는 부분 보다 더 앞에 있어야 할 듯.

2021-12-24 03:06 UTC, iolo commented on src/date-util/date-util.ts
> +
[Intl.DateTimeFormat](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)을 활용해보면 어떨까요?

2021-12-24 03:46 UTC, pkiop commented on src/date-util/date-util.ts
> +          return `${dateInfo.year}`.padStart(2, '0');
`2022.padStart(2, '0') // 2022`
YY 면 22 가 나와야할 것 같은데 2022가 나오도록 되어 있습니다
```suggestion
          return String(dateInfo.year % 100).padStart(2, '0');
```
은 어떨까요?

YY 테스트 코드도 추가하면 좋을 것 같습니다!

2021-12-27 05:53 UTC, moonimooni commented on src/date-util/date-util.ts
> +    if (format === DEFAULT_LOCALE_DATE_FORMAT) {
이유가 뭔지 여쭤봐도 될까요?

2021-12-27 06:31 UTC, moonimooni commented on src/date-util/date-util.ts
> +
format함수에 Intl.DateTimeFormat을 적용해보라는 말씀이신가요?

Intl.DateTimeFormat을 사용하면 우려되는 점이 몇가지 있습니다.
1. iso 포맷 지원 X
 -> 현재 util 스펙은 format 함수가 iso format을 디폴트로 제공하고 있는데 Intl.DateTimeFormat은 iso 포맷을 사용할 수 없어, 스웨덴이나 캐나다 로케일을 강제로 주입하고 추가 가공을 해야 하는데, 이 방식이 맞을지 잘 모르겠습니다.
 https://stackoverflow.com/questions/25050034/get-iso-8601-using-intl-datetimeformat
 
2. 기존처럼 자유롭게 포맷팅을 하던 방식에 제약이 걸릴 것 같은데 괜찮을까요?
```javascript
const TIMESTAMP_FORMAT = 'YYYYMMDDHHmmssSSS';
const DATEHOUR_FORMAT = 'YYYYMMDDHH';
const DATE_FORMAT_VARIANT1 = 'MMM Do dddd';
const DATE_FORMAT_VARIANT2 = 'YY/MM/DD(ddd)';
const DATE_FORMAT_VARIANT3 = 'YYYY년 M월 D일 HH:mm';
// 등등 ...

function formatDateHour() { format(date, DATEHOUR_FORMAT) } // intl.DateTimeFormat 사용시 어려움이 있음
```

2021-12-27 07:27 UTC, moonimooni commented on src/date-util/date-util.ts
> +          return `${dateInfo.year}`.padStart(2, '0');
수정하고 테스트코드 추가했습니다!

2022-01-07 06:18 UTC, iolo approved these changes
go ahead!

2022-01-07 06:58 UTC, merged